// Supabase connection for the live site (generated by scripts/write-config.mjs).
// Public anon key only — Row Level Security makes it read-only. Never the service_role key.
window.POSTIT_CONFIG = {
  SUPABASE_URL: "https://hooxyhsuckpekksdoytw.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhvb3h5aHN1Y2twZWtrc2RveXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyNDExOTYsImV4cCI6MjEwNjgxNzE5Nn0.zD5JttJOMMgWqAvU9cfD57MumcAGMHTrLQxUi35kD6c",
};
