#!/usr/bin/env node
// Writes config.js from env vars so the site talks to Supabase:
//   SUPABASE_URL=https://<ref>.supabase.co SUPABASE_ANON_KEY=<public anon key> node scripts/write-config.mjs
// Only the PUBLIC anon key belongs in config.js (RLS keeps it read-only). Refuses service_role keys.
import { writeFileSync } from "node:fs";

const url = (process.env.SUPABASE_URL || "").trim().replace(/\/+$/, "");
const key = (process.env.SUPABASE_ANON_KEY || "").trim();
if (!/^https?:\/\/.+/.test(url) || !key) {
  console.error("Set SUPABASE_URL (https://<ref>.supabase.co) and SUPABASE_ANON_KEY first.");
  process.exit(1);
}
// Legacy JWT keys carry a role claim; new-style keys use sb_publishable_ / sb_secret_ prefixes.
let role = "";
try { role = JSON.parse(Buffer.from(key.split(".")[1], "base64url").toString()).role || ""; } catch { /* not a JWT */ }
if (role === "service_role" || key.startsWith("sb_secret_")) {
  console.error("Refusing: that is a SECRET/service key. Use the public anon (publishable) key.");
  process.exit(1);
}
const out = `// Supabase connection for the live site (generated by scripts/write-config.mjs).
// Public anon key only — Row Level Security makes it read-only. Never the service_role key.
window.POSTIT_CONFIG = {
  SUPABASE_URL: ${JSON.stringify(url)},
  SUPABASE_ANON_KEY: ${JSON.stringify(key)},
};
`;
writeFileSync(new URL("../config.js", import.meta.url), out);
console.log("Wrote config.js for", url);
